version: '3'

services:
  jira:
    container_name: jira
    depends_on:
      - postgresql
    image: atlassian/jira-software:8.5.4
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8001:8080'
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/jiradb'
      - 'ATL_JDBC_USER=admin'
      - 'ATL_JDBC_PASSWORD=admin'
      - 'SETENV_JVM_MINIMUM_MEMORY=2048m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=4096m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql
    expose:
      - '5432'
    networks:
      - jiranet
    volumes:
      - postgresqldata:/var/postgresql/data
    environment:
      - 'POSTGRESQL_USERNAME=admin'
      - 'POSTGRESQL_PASSWORD=admin'
      - 'POSTGRESQL_DATABASE=admin'
      - 'POSTGRESQL_REPLICATION_USER=my_repl_user'
      - 'POSTGRESQL_REPLICATION_PASSWORD=my_repl_password'

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge